---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/pr-labels.yaml@ecc3b31c93db7eb6327250ff37df8a29f8780094 # main
